export const DEMONYM_AND_COUNTRIES = {
  Afghan: 'Afghanistan',
  Algerian: 'Algeria',
  Angolan: 'Angola',
  Argentine: 'Argentina',
  Austrian: 'Austria',
  Australian: 'Australia',
  Bangladeshi: 'Bangladesh',
  Belarusian: 'Belarus',
  Belgian: 'Belgium',
  Bolivian: 'Bolivia',
  'Bosnian/Herzegovinian': 'Bosnia and Herzegovina',
  Brazilian: 'Brazil',
  British: 'The United Kingdom',
  Bulgarian: 'Bulgaria',
  Cambodian: 'Cambodia',
  Cameroonian: 'Cameroon',
  Canadian: 'Canada',
  'Central African': 'Central African Republic',
  Chadian: 'Chad',
  Chinese: 'China',
  Colombian: 'Colombia',
  'Costa Rican': 'Costa Rica',
  Croatian: 'Croatia',
  Czech: 'the Czech Republic',
  Congolese: 'Democratic Republic of the Congo',
  Danish: 'Denmark',
  Ecuadorian: 'Ecuador',
  Egyptian: 'Egypt',
  Salvadoran: 'El Salvador',
  English: 'England',
  Estonian: 'Estonia',
  Ethiopian: 'Ethiopia',
  Finnish: 'Finland',
  French: 'France',
  German: 'Germany',
  Ghanaian: 'Ghana',
  Greek: 'Greece',
  Guatemalan: 'Guatemala',
  Dutch: 'Holland',
  Honduran: 'Honduras',
  Hungarian: 'Hungary',
  Icelandic: 'Iceland',
  Indian: 'India',
  Indonesian: 'Indonesia',
  Iranian: 'Iran',
  Iraqi: 'Iraq',
  Irish: 'Ireland',
  Israeli: 'Israel',
  Italian: 'Italy',
  Ivorian: 'Ivory Coast',
  Jamaican: 'Jamaica',
  Japanese: 'Japan',
  Jordanian: 'Jordan',
  Kazakh: 'Kazakhstan',
  Kenyan: 'Kenya',
  Lao: 'Laos',
  Latvian: 'Latvia',
  Libyan: 'Libya',
  Lithuanian: 'Lithuania',
  Malagasy: 'Madagascar',
  Malaysian: 'Malaysia',
  Malian: 'Mali',
  Mauritanian: 'Mauritania',
  Mexican: 'Mexico',
  Moroccan: 'Morocco',
  Namibian: 'Namibia',
  'New Zealand': 'New Zealand',
  Nicaraguan: 'Nicaragua',
  Nigerien: 'Niger',
  Nigerian: 'Nigeria',
  Norwegian: 'Norway',
  Omani: 'Oman',
  Pakistani: 'Pakistan',
  Panamanian: 'Panama',
  Paraguayan: 'Paraguay',
  Peruvian: 'Peru',
  Philippine: 'The Philippines',
  Polish: 'Poland',
  Portuguese: 'Portugal',
  Romanian: 'Romania',
  Russian: 'Russia',
  'Saudi, Saudi Arabian': 'Saudi Arabia',
  Scottish: 'Scotland',
  Senegalese: 'Senegal',
  Serbian: 'Serbia',
  Singaporean: 'Singapore',
  Slovak: 'Slovakia',
  Somalian: 'Somalia',
  'South African': 'South Africa',
  Spanish: 'Spain',
  Sudanese: 'Sudan',
  Swedish: 'Sweden',
  Swiss: 'Switzerland',
  Syrian: 'Syria',
  Thai: 'Thailand',
  Tunisian: 'Tunisia',
  Turkish: 'Turkey',
  Turkmen: 'Turkmenistan',
  Ukranian: 'Ukraine',
  Emirati: 'The United Arab Emirates',
  American: 'The United States',
  Uruguayan: 'Uruguay',
  Vietnamese: 'Vietnam',
  Welsh: 'Wales',
  Zambian: 'Zambia',
  Zimbabwean: 'Zimbabwe',
};

//
// export {
//   DEMONYM_AND_COUNTRIES
// };
